### PR TITLE
Fix position of dropdown when displayed above input

### PR DESCRIPTION
**Pull request by bshamblen**
@lnader Please review for Unity issue #3195.

### CODE REVIEW

**Comment by lnader** [comment]
@bshamblen - It looks ok to me.  Does this work well in other places it is used.?

**Comment by bshamblen** [comment]
I tested it in several places, but it's used a lot. it's hard to say for sure, without testing every single instance. I would need help generating use cases to cause it to display for every occurance, since it's used in areas of the app that I haven't been in before.

**Comment by bshamblen** [comment]
@lnader I think I found the case where my change doesn't work. In the process design footer bar, if the footer isn't tall enough to fit the content of the "add property" drop down, the drop down is displayed on the top, but is hidden behind the table header. Please don't merge yet.

**Comment by bshamblen** [comment]
@lnader @rflow I found the root cause of why this dropdown doesn't position correctly in a modal. Quote from the CSS documentation regarding the `fixed` position setting:

> When an ancestor has the transform property set to something different than none then this ancestor is used as container instead of the viewport

So, in this case, the `modal-dialog` class that's applied to the current modal has the `transform` applied to give the transition effect of growing from the center of the screen. Because of this, when the autocomplete tries to position the content above the input box, it's using the top left corner of the modal as the `position` anchor, not the top left corner of the document. 

I've committed a change that should resolve the issue.

**Pull request merged**
